# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1384, 900)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # ── QTabWidget principal ──────────────────────────────────────────
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1384, 900))
        self.tabWidget.setObjectName("tabWidget")

        # ═══════════════════════════════════════════════════════════════════
        # PESTAÑA 1 — Mes actual
        # ═══════════════════════════════════════════════════════════════════
        self.tab_mes = QtWidgets.QWidget()
        self.tab_mes.setObjectName("tab_mes")

        # Selector de mes
        self.mes_label = QtWidgets.QLabel(self.tab_mes)
        self.mes_label.setGeometry(QtCore.QRect(20, 10, 50, 28))
        font = QtGui.QFont(); font.setPointSize(12)
        self.mes_label.setFont(font)
        self.mes_label.setObjectName("mes_label")

        self.mes_combo = QtWidgets.QComboBox(self.tab_mes)
        self.mes_combo.setGeometry(QtCore.QRect(75, 7, 596, 28))
        font = QtGui.QFont(); font.setPointSize(12)
        self.mes_combo.setFont(font)
        self.mes_combo.setObjectName("mes_combo")

        # GroupBox Añadir
        self.groupBox = QtWidgets.QGroupBox(self.tab_mes)
        self.groupBox.setGeometry(QtCore.QRect(20, 48, 651, 251))
        self.groupBox.setObjectName("groupBox")

        # Radio Gasto
        self.radioButton = QtWidgets.QRadioButton(self.tab_mes)
        self.radioButton.setGeometry(QtCore.QRect(40, 68, 91, 51))
        font = QtGui.QFont(); font.setPointSize(14)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")

        # Radio Ingreso
        self.radioButton_2 = QtWidgets.QRadioButton(self.tab_mes)
        self.radioButton_2.setGeometry(QtCore.QRect(140, 78, 121, 31))
        font = QtGui.QFont(); font.setPointSize(14)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")

        # Label Nombre
        self.label = QtWidgets.QLabel(self.tab_mes)
        self.label.setGeometry(QtCore.QRect(30, 158, 111, 31))
        font = QtGui.QFont(); font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")

        # NameText
        self.NameText = QtWidgets.QTextEdit(self.tab_mes)
        self.NameText.setGeometry(QtCore.QRect(140, 148, 281, 41))
        self.NameText.setObjectName("NameText")

        # Label Valor
        self.label_2 = QtWidgets.QLabel(self.tab_mes)
        self.label_2.setGeometry(QtCore.QRect(30, 218, 71, 41))
        font = QtGui.QFont(); font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        # ValueText
        self.ValueText = QtWidgets.QTextEdit(self.tab_mes)
        self.ValueText.setGeometry(QtCore.QRect(140, 218, 281, 41))
        self.ValueText.setObjectName("ValueText")

        # Botón OK
        self.pushButton = QtWidgets.QPushButton(self.tab_mes)
        self.pushButton.setGeometry(QtCore.QRect(440, 148, 61, 111))
        font = QtGui.QFont(); font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        # Gráfico distribución de gastos
        self.Gastos_Graph = QtWidgets.QGraphicsView(self.tab_mes)
        self.Gastos_Graph.setGeometry(QtCore.QRect(20, 318, 661, 511))
        self.Gastos_Graph.setObjectName("Gastos_Graph")

        # Gráfico ingresos vs gastos
        self.GastosIngresos_Graph = QtWidgets.QGraphicsView(self.tab_mes)
        self.GastosIngresos_Graph.setGeometry(QtCore.QRect(700, 318, 641, 511))
        self.GastosIngresos_Graph.setObjectName("GastosIngresos_Graph")

        # Resumen con scroll
        self.resumen_label = QtWidgets.QTextEdit(self.tab_mes)
        self.resumen_label.setGeometry(QtCore.QRect(700, 22, 641, 280))
        font = QtGui.QFont(); font.setPointSize(12)
        self.resumen_label.setFont(font)
        self.resumen_label.setReadOnly(True)
        self.resumen_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.resumen_label.setObjectName("resumen_label")

        # Z-order pestaña 1
        self.groupBox.raise_()
        self.mes_label.raise_()
        self.mes_combo.raise_()
        self.radioButton.raise_()
        self.radioButton_2.raise_()
        self.label.raise_()
        self.NameText.raise_()
        self.label_2.raise_()
        self.ValueText.raise_()
        self.pushButton.raise_()
        self.Gastos_Graph.raise_()
        self.GastosIngresos_Graph.raise_()
        self.resumen_label.raise_()

        self.tabWidget.addTab(self.tab_mes, "")

        # ═══════════════════════════════════════════════════════════════════
        # PESTAÑA 2 — Comparación
        # ═══════════════════════════════════════════════════════════════════
        self.tab_comparacion = QtWidgets.QWidget()
        self.tab_comparacion.setObjectName("tab_comparacion")

        # GroupBox selector
        self.groupBox_comp = QtWidgets.QGroupBox(self.tab_comparacion)
        self.groupBox_comp.setGeometry(QtCore.QRect(20, 10, 1340, 65))
        self.groupBox_comp.setObjectName("groupBox_comp")

        # Label Mes A
        self.label_mes_a = QtWidgets.QLabel(self.tab_comparacion)
        self.label_mes_a.setGeometry(QtCore.QRect(35, 38, 60, 28))
        font = QtGui.QFont(); font.setPointSize(12)
        self.label_mes_a.setFont(font)
        self.label_mes_a.setObjectName("label_mes_a")

        # ComboBox Mes A
        self.comp_combo_a = QtWidgets.QComboBox(self.tab_comparacion)
        self.comp_combo_a.setGeometry(QtCore.QRect(100, 35, 220, 28))
        font = QtGui.QFont(); font.setPointSize(12)
        self.comp_combo_a.setFont(font)
        self.comp_combo_a.setObjectName("comp_combo_a")

        # Label Mes B
        self.label_mes_b = QtWidgets.QLabel(self.tab_comparacion)
        self.label_mes_b.setGeometry(QtCore.QRect(345, 38, 60, 28))
        font = QtGui.QFont(); font.setPointSize(12)
        self.label_mes_b.setFont(font)
        self.label_mes_b.setObjectName("label_mes_b")

        # ComboBox Mes B
        self.comp_combo_b = QtWidgets.QComboBox(self.tab_comparacion)
        self.comp_combo_b.setGeometry(QtCore.QRect(410, 35, 220, 28))
        font = QtGui.QFont(); font.setPointSize(12)
        self.comp_combo_b.setFont(font)
        self.comp_combo_b.setObjectName("comp_combo_b")

        # Resumen de diferencias
        self.comp_resumen = QtWidgets.QTextEdit(self.tab_comparacion)
        self.comp_resumen.setGeometry(QtCore.QRect(20, 90, 400, 740))
        font = QtGui.QFont(); font.setPointSize(11)
        self.comp_resumen.setFont(font)
        self.comp_resumen.setReadOnly(True)
        self.comp_resumen.setObjectName("comp_resumen")

        # Gráfico barras por categoría
        self.comp_graph_categorias = QtWidgets.QGraphicsView(self.tab_comparacion)
        self.comp_graph_categorias.setGeometry(QtCore.QRect(435, 90, 930, 360))
        self.comp_graph_categorias.setObjectName("comp_graph_categorias")

        # Gráfico tendencia todos los meses
        self.comp_graph_tendencia = QtWidgets.QGraphicsView(self.tab_comparacion)
        self.comp_graph_tendencia.setGeometry(QtCore.QRect(435, 465, 930, 365))
        self.comp_graph_tendencia.setObjectName("comp_graph_tendencia")

        # Z-order pestaña 2
        self.groupBox_comp.raise_()
        self.label_mes_a.raise_()
        self.comp_combo_a.raise_()
        self.label_mes_b.raise_()
        self.comp_combo_b.raise_()
        self.comp_resumen.raise_()
        self.comp_graph_categorias.raise_()
        self.comp_graph_tendencia.raise_()

        self.tabWidget.addTab(self.tab_comparacion, "")

        # ── StatusBar & central widget ────────────────────────────────────
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Chiclin"))
        # Pestaña 1
        self.tabWidget.setTabText(0, _translate("MainWindow", "Mes actual"))
        self.mes_label.setText(_translate("MainWindow", "Mes:"))
        self.groupBox.setTitle(_translate("MainWindow", "Añadir"))
        self.radioButton.setText(_translate("MainWindow", "Gasto"))
        self.radioButton_2.setText(_translate("MainWindow", "Ingreso"))
        self.label.setText(_translate("MainWindow", "Nombre:"))
        self.label_2.setText(_translate("MainWindow", "Valor"))
        self.pushButton.setText(_translate("MainWindow", "OK"))
        # Pestaña 2
        self.tabWidget.setTabText(1, _translate("MainWindow", "Comparación"))
        self.groupBox_comp.setTitle(_translate("MainWindow", "Seleccionar meses"))
        self.label_mes_a.setText(_translate("MainWindow", "Mes A:"))
        self.label_mes_b.setText(_translate("MainWindow", "Mes B:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())